USE [master]
GO

/****** Object:  Database [cribrn]    Script Date: 10/11/2014 06:35:14 ******/
CREATE DATABASE [cribrn]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'cribrn', FILENAME = N'f:\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\cribrn.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'cribrn_log', FILENAME = N'f:\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\cribrn_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [cribrn] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cribrn].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [cribrn] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [cribrn] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [cribrn] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [cribrn] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [cribrn] SET ARITHABORT OFF 
GO

ALTER DATABASE [cribrn] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [cribrn] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [cribrn] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [cribrn] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [cribrn] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [cribrn] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [cribrn] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [cribrn] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [cribrn] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [cribrn] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [cribrn] SET  DISABLE_BROKER 
GO

ALTER DATABASE [cribrn] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [cribrn] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [cribrn] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [cribrn] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [cribrn] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [cribrn] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [cribrn] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [cribrn] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [cribrn] SET  MULTI_USER 
GO

ALTER DATABASE [cribrn] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [cribrn] SET DB_CHAINING OFF 
GO

ALTER DATABASE [cribrn] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [cribrn] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [cribrn] SET  READ_WRITE 
GO

